import { BOSS_TACTICS, monsterRecordFor, damageMultiplierFor, type DamageKind } from "./monsters.ts";
import { retreatEnemyAfterEscape } from "./escape.ts";
import { stats, SKILL_COSTS, INTENTS, statusName, statusFor, statusDamage, statusText, nextIntentFor, nextRandom, passivePower, supplyName, supplyUnavailableReason } from "./game-rules.ts";
import type { Run, BattleEnemy, OwnedGear, SupplyId, StatusKind, FinishDetail, GameNotice, EnemyIntent } from "./game-types.ts";
import type { BattleCommand } from "./battle-presentation.ts";
export type BattleResolution={run:Run;victory:BattleEnemy|null;death:FinishDetail|null};
const queueEnemyTurn=(g:Run,b:BattleEnemy,message:string,skip=false):Run=>({...g,battle:b,message,pendingEnemyTurn:{battle:b,message,skip}});

export const victoryRun=(g:Run,b:BattleEnemy,graveItems:OwnedGear[]=[]):Run=>{if(b.graveEater)return{...g,phase:graveItems.length?"recoveryChoice":"explore",battle:null,pendingEnemyTurn:null,enemies:g.enemies.filter(e=>e.id!==b.id),recovery:graveItems,message:"遺品喰らいを倒した！"};const exp=g.exp+b.exp;let level=g.level;let remain=exp;let hp=g.hp,mp=g.mp;while(remain>=level*12){remain-=level*12;level++;hp+=5;mp+=2;}const bosses=g.bosses+(b.boss?1:0),combo=g.combo+1,echo=combo%3===0,final=b.boss&&g.floor===100;const echoHeal=echo?Math.ceil(stats(g).maxHp*.15):0,bloodHeal=g.relics?.includes("r1")?4:0,gold=Math.ceil(b.gold*(g.relics?.includes("r2")?1.15:1));hp=Math.min(stats({...g,level}).maxHp,hp+echoHeal+bloodHeal);mp=Math.min(stats({...g,level}).maxMp,mp);const gotBomb=echo&&g.bombs<2;const next={...g,relics:final?[...new Set([...g.relics,"r10"])]:g.relics,phase:(final?"ending":b.boss?"relicChoice":"explore") as Run["phase"],battle:null,pendingEnemyTurn:null,enemies:g.enemies.filter(e=>e.id!==b.id),gold:g.gold+gold,totalGold:g.totalGold+gold,kills:g.kills+1,bosses,combo,bombs:gotBomb?g.bombs+1:g.bombs,level,exp:remain,hp,mp,message:final?"百景の奈落王は霧となって消えた。地下百景、踏破。":`${b.name}を倒した！ ${gold}Gを得た。${bloodHeal?` 血の杯でHPを${bloodHeal}回復。`:""}${echo?` 魂火連鎖！ HPを${echoHeal}回復${gotBomb?"、爆裂石を得た":""}。`:""}${b.boss?" 遺物を1つ選べ。":""}${level>g.level?` レベル${level}へ！`:""}`};return next;};

function withBattleNotice(old:Run,next:Run,command:string,enemyIntent:EnemyIntent|undefined,victory:boolean,dead:boolean):Run {
  if(next===old)return old;
  const notice:GameNotice={type:"combat",command,enemyIntent,
    playerDamage:Math.max(0,old.hp-next.hp),enemyDamage:Math.max(0,(old.battle?.hp??0)-(next.battle?.hp??0)),
    healing:Math.max(0,next.hp-old.hp),enemyHealing:Math.max(0,(next.battle?.hp??0)-(old.battle?.hp??0)),
    mpChange:next.mp-old.mp,status:next.statuses.map(s=>s.kind),victory,dead};
  if(command==="enemy"&&old.notice?.type==="combat"){
    notice.command=old.notice.command;notice.playerDamage+=old.notice.playerDamage;notice.enemyDamage+=old.notice.enemyDamage;
    notice.healing+=old.notice.healing;notice.enemyHealing+=old.notice.enemyHealing;notice.mpChange+=old.notice.mpChange;
  }
  return {...next,notice};
}

export function resolveBattleAction(g:Run,mode:BattleCommand,graveItems:OwnedGear[]=[]):BattleResolution{
  let victory:BattleEnemy|null=null,death:FinishDetail|null=null;
  const win=(run:Run,battle:BattleEnemy):Run=>{victory=battle;return victoryRun(run,battle,graveItems);};
  const act=(g:Run):Run=>{if(!g||g.phase!=="battle"||!g.battle||g.pendingEnemyTurn)return g;let b={...g.battle},next={...g},message="";const st=stats(g),record=monsterRecordFor(b.catalogId),bossTactic=b.boss?BOSS_TACTICS[g.floor]:undefined,trait=bossTactic?.trait??record.trait,affinityTarget=bossTactic??record;let [r,seed]=nextRandom(g.seed);next.seed=seed;if(mode!=="potion"&&g.statuses.some(status=>status.kind==="paralysis")&&r<.28)return queueEnemyTurn(next,b,"麻痺で体が動かない！");if(mode==="guard"){next.guard=.4;return queueEnemyTurn(next,b,"防御の構え。");}if(mode==="potion"){if(g.potions<=0)return{...g,message:"回復薬を持っていない。"};const heal=Math.min(Math.max(18,Math.ceil(st.maxHp*.45)),st.maxHp-g.hp);next.potions--;next.hp+=heal;next.statuses=[];return queueEnemyTurn(next,b,`回復薬でHPを${heal}回復した。`);}if(mode==="bomb"){if(g.bombs<=0)return{...g,message:"爆裂石を持っていない。"};next.bombs--;const baseDamage=Math.max(24,Math.ceil(b.maxHp*.38)+g.floor),guardScale=b.intent==="guard"?(trait==="shell"?.18:trait==="shieldWall"?.25:.55):1,affinity=damageMultiplierFor(affinityTarget,"blast"),damage=Math.max(1,Math.floor(baseDamage*affinity*guardScale));b.hp-=damage;if(b.hp<=0)return win(next,b);return queueEnemyTurn(next,b,`爆裂石が砕け、${damage}の傷を与えた！${affinity>1?" 弱点を突いた！":""}${guardScale<1?" 敵の防御に阻まれた。":""}`);}if(mode==="flee"){if(b.boss)return{...g,message:"階層主からは逃げられない！"};if(r<.65+(g.job==="thief"?.2:0))return{...g,phase:"explore",battle:null,pendingEnemyTurn:null,enemies:retreatEnemyAfterEscape(g.map,g.player,g.enemies,b.id),message:"闇へ身を隠し、敵を振り切った。"};return queueEnemyTurn(next,b,"逃げ道を塞がれた！");}
    let damage=0,skip=false,damageKind:DamageKind="physical";if(mode==="attack"){damage=Math.max(1,st.atk-b.def+Math.floor(r*4));message=`${g.name}の攻撃。`;}else{const which=mode==="skill1"?0:1;const cost=SKILL_COSTS[g.job][which];if(g.mp<cost)return{...g,message:"MPが足りない。"};next.mp-=cost;if(g.job==="warrior"){if(which===0){damage=Math.max(1,Math.floor(st.atk*1.8)-b.def);message=`強打！`;}else{next.guard=.35;message="盾を構え、次の攻撃に備えた。";}}if(g.job==="thief"){if(which===0){damage=Math.max(2,Math.floor(st.atk*1.45)-b.def);message=`連撃！`;}else{const gain=4+g.floor;next.gold+=gain;next.totalGold+=gain;message=`${gain}Gを盗んだ。`;}}if(g.job==="priest"){if(which===0){const heal=Math.min(12+g.level*3,st.maxHp-g.hp);next.hp+=heal;message=`治療の祈り。HPが${heal}回復。`;}else{next.guard=.3;message="守りの祈りが身を包む。";}}if(g.job==="mage"){damage=which===0?10+g.level*4:7+g.level*3;damageKind=which===0?"fire":"ice";skip=which===1&&r<.45;message=which===0?`火球が弾けた！`:`氷結が走った！`; }if(g.job==="knight"){if(which===0){damage=Math.max(2,Math.floor(st.atk*1.4)-b.def);damageKind="blast";skip=r<.3;message=`盾打ち！`;}else{next.guard=.2;message="鉄壁の構えを取った。";}}if(g.job==="sage"){if(which===0){const heal=Math.min(20+g.level*4,st.maxHp-g.hp);next.hp+=heal;message=`大治療。HPが${heal}回復。`;}else{damage=14+g.level*5;damageKind="lightning";message=`雷撃が落ちた！`;}}if(g.job==="samurai"){if(which===0){damage=Math.max(3,Math.floor(st.atk*2.1)-b.def);message="居合斬り！";}else{next.guard=.22;message="見切りの構え。次の一撃を読む。";}}if(g.job==="alchemist"){if(which===0){damage=Math.max(24,Math.ceil(b.maxHp*.42)+g.floor);damageKind="blast";message="爆薬調合が炸裂した！";}else{const heal=Math.min(16+g.level*3,st.maxHp-next.hp);next.hp+=heal;next.mp=Math.min(st.maxMp,next.mp+3);next.statuses=[];message=`再生調合。HPが${heal}回復し、状態異常を洗い流した。`;}}}
    if(damage>0&&g.statuses.some(status=>status.kind==="blind")&&r<.32){damage=0;message="暗闇で攻撃を外した！";}else if(damage>0&&trait==="fireAbsorb"&&damageKind==="fire"){const absorbed=Math.min(b.maxHp-b.hp,Math.max(1,Math.ceil(damage*.65)));b.hp+=absorbed;damage=0;message=`${b.name}は炎を吸収し、HPを${absorbed}回復した！`;}else if(damage>0&&trait==="magicMirror"&&(["fire","ice","lightning","holy"] as DamageKind[]).includes(damageKind)){const reflected=Math.max(1,Math.ceil(damage*.3));next.hp=Math.max(0,next.hp-reflected);damage=0;message=`${b.name}の鏡面が魔法を反射。${g.name}は${reflected}の傷！`;if(next.hp<=0){const deathMessage=`${message} 反射で倒れた……`;death={cause:"reflect",intent:b.intent};return{...next,hp:0,battle:b,message:deathMessage};}}else if(damage>0){const affinity=damageMultiplierFor(affinityTarget,damageKind),guardScale=b.intent==="guard"?(trait==="shell"?.18:trait==="shieldWall"?.25:.55):1,lastStand=passivePower(g,"lastStand"),criticalChance=passivePower(g,"critical")+(g.relics?.includes("r6")?18:0);let combatNote="";damage=Math.max(1,Math.floor(damage*affinity*guardScale));if(lastStand&&g.hp/st.maxHp<=.35){damage=Math.ceil(damage*(1+lastStand/100));combatNote+=` 瀕死強化！`;}if(criticalChance&&r<criticalChance/100){damage=Math.ceil(damage*1.75);combatNote+=` 会心！`;}if(affinity>1)combatNote+=` 弱点を突いた！`;else if(affinity<1)combatNote+=` 耐性に阻まれた。`;if(guardScale<1)combatNote+=trait==="shell"||trait==="shieldWall"?` 強固な守りにほぼ弾かれた。`:` 防御で軽減された。`;if((trait==="curseCounter"||trait==="bleedCounter")&&b.intent==="guard"){const counterKind=trait==="curseCounter"?"curse":"bleed";next.statuses=[...next.statuses.filter(status=>status.kind!==counterKind),{kind:counterKind,turns:3}];combatNote+=` ${counterKind==="curse"?"呪い":"出血"}の反撃を受けた。`; }const vampire=passivePower(g,"vampire"),mpFlow=passivePower(g,"mpFlow"),healed=vampire?Math.min(st.maxHp-next.hp,Math.max(1,Math.floor(damage*vampire/100))):0,restoredMp=mpFlow?Math.min(st.maxMp-next.mp,mpFlow):0;if(healed){next.hp+=healed;combatNote+=` 吸血でHP${healed}回復。`;}if(restoredMp){next.mp+=restoredMp;combatNote+=` MP循環で${restoredMp}回復。`;}message+=` ${damage}の傷。${combatNote}`;}
    b.hp-=damage;if(b.hp>0&&trait==="split"&&!b.traitUsed&&b.hp<=b.maxHp*.5){const restored=Math.ceil(b.maxHp*.28);b.hp=Math.min(b.maxHp,b.hp+restored);b.traitUsed=true;message+=` 苔スライムが分裂し、HPを${restored}戻した！`;}if(b.hp<=0)return win(next,b);return queueEnemyTurn(next,b,message,skip);};
  const next=act(g);
  return {run:withBattleNotice(g,next,mode,undefined,Boolean(victory),Boolean(death)),victory,death};
}

export function resolveEnemyTurn(g:Run,b:BattleEnemy,message:string,skip=false,graveItems:OwnedGear[]=[]):BattleResolution{
  let victory:BattleEnemy|null=null,death:FinishDetail|null=null;
  const win=(run:Run,battle:BattleEnemy):Run=>{victory=battle;return victoryRun(run,battle,graveItems);};
  const act=(g:Run,b:BattleEnemy,message:string,skip=false):Run=>{
    const current=INTENTS[b.intent], record=monsterRecordFor(b.catalogId), bossTactic=b.boss?BOSS_TACTICS[g.floor]:undefined, trait=bossTactic?.trait??record.trait, activeStatuses=g.statuses;
    if(g.relics?.includes("r9")&&current.multiplier>0&&((g.seed+b.turn*17)%100)<16){const stopped={...b,turn:b.turn+1};return{...g,battle:{...stopped,intent:nextIntentFor(stopped,g.floor,stopped.turn)},guard:0,message:`${message} 時止めの砂が敵の行動を止めた！`};}
    const turn=b.turn+1, advancedBase={...b,turn}, nextIntent=nextIntentFor(advancedBase,g.floor,turn), restingHeal=trait==="regenerate"&&(b.intent==="guard"||b.intent==="charge")?Math.max(1,Math.ceil(b.maxHp*.08)):0, advanced={...advancedBase,intent:nextIntent,hp:Math.min(b.maxHp,advancedBase.hp+restingHeal)};
    if(skip||current.multiplier===0){
      if(b.intent==="status"&&!skip){const kind=statusFor(b,g.floor),resist=passivePower(g,"statusResist"),resisted=resist>0&&((g.seed+b.turn*29)%100)<resist;if(resisted)return{...g,statuses:activeStatuses,battle:advanced,guard:0,message:`${message} 装備の状態耐性が${statusName[kind]}を防いだ！ 次は${INTENTS[nextIntent].label}。`};const turns=g.guard?1:3;const kept=activeStatuses.filter(s=>s.kind!==kind);return{...g,statuses:[...kept,{kind,turns}],battle:advanced,guard:0,message:`${message} ${b.name}の呪気で${statusName[kind]}になった。${g.guard?"防御で効果を1ターンに抑えた。":""} 次は${INTENTS[nextIntent].label}。`};}
      return{...g,statuses:activeStatuses,battle:advanced,guard:0,message:`${message} ${skip?"敵は動けない！":`${b.name}は${current.label}。攻撃してこない。`}${restingHeal?` HPを${restingHeal}再生。`:""} 次は${INTENTS[nextIntent].label}。${statusText(activeStatuses)}`};
    }

    const st=stats(g), curse=activeStatuses.some(s=>s.kind==="curse")?1.25:1,attackScale=trait==="multiHit"&&b.intent==="attack"?1.14:trait==="tripleHit"&&b.intent==="attack"?1.22:trait==="flameSurge"&&b.intent==="heavy"?1.18:trait==="execute"&&g.hp/st.maxHp<=.35?1.3:1,defense=trait==="armorPierce"?Math.floor(st.def*.45):st.def;
    const dmg=Math.max(1,Math.floor((b.atk*current.multiplier-defense)*(g.guard||1)*curse*attackScale)+Math.floor(g.seed%3));
    const stolen=trait==="steal"?Math.min(g.gold,2+g.floor):0,drained=trait==="drain"?Math.max(1,Math.ceil(dmg*.35)):0,resolvedBattle=drained?{...advanced,hp:Math.min(advanced.maxHp,advanced.hp+drained)}:advanced;
    const mpStolen=trait==="manaDrain"?Math.min(g.mp,2+Math.floor(g.floor/30)):0,resist=passivePower(g,"statusResist"),paralyzeTriggered=trait==="paralyzeStrike"&&b.intent==="attack"&&((g.seed+b.turn*13)%4===0),paralyzed=paralyzeTriggered&&!(((g.seed+b.turn*29)%100)<resist),addedStatuses=paralyzed?[...activeStatuses.filter(status=>status.kind!=="paralysis"),{kind:"paralysis" as StatusKind,turns:2}]:activeStatuses;
    const counterPower=g.guard?passivePower(g,"guardCounter"):0,counterDamage=counterPower?Math.max(1,Math.floor(st.atk*counterPower/100)):0,counteredBattle=counterDamage?{...resolvedBattle,hp:resolvedBattle.hp-counterDamage}:resolvedBattle;
    const dot=statusDamage(activeStatuses), hp=g.hp-dmg-dot, statuses=addedStatuses.map(s=>({...s,turns:s.turns-1})).filter(s=>s.turns>0),traitText=`${trait==="multiHit"?" 二連噛み！":trait==="tripleHit"?" 三連撃！":""}${trait==="armorPierce"?" 守備を貫いた。":""}${trait==="flameSurge"&&b.intent==="heavy"?" 火柱が膨れ上がった！":""}${trait==="execute"&&attackScale>1?" 瀕死狩り！":""}${drained?` ${drained}HPを吸収。`:""}${stolen?` ${stolen}Gを盗まれた。`:""}${mpStolen?` MPを${mpStolen}奪われた。`:""}${paralyzed?" 麻痺針が刺さった。":paralyzeTriggered&&resist?" 状態耐性で麻痺を防いだ！":""}${counterDamage?` 盾の反撃で${counterDamage}の傷！`:""}`;
    if(hp<=0){const deathMessage=`${message} ${b.name}の${current.label}で倒れた……`;death={cause:dot>0?"status":b.intent==="heavy"?"heavy":"enemy",intent:b.intent};return{...g,hp:0,mp:g.mp-mpStolen,gold:g.gold-stolen,statuses,battle:counteredBattle,message:deathMessage};}
    if(counteredBattle.hp<=0){const victory=win({...g,hp,mp:g.mp-mpStolen,gold:g.gold-stolen,statuses},counteredBattle);return{...victory,message:`${victory.message} 防御反撃が決め手になった！`};}
    return{...g,hp,mp:g.mp-mpStolen,gold:g.gold-stolen,statuses,battle:counteredBattle,guard:0,message:`${message} ${b.name}の${current.label}、${dmg}の傷。${traitText}${dot?` ${dot}の継続ダメージ。`:""} 次は${INTENTS[nextIntent].label}。${statusText(statuses)}`};
  };
  const next=act(g,b,message,skip);
  return {run:withBattleNotice(g,next,"enemy",b.intent,Boolean(victory),Boolean(death)),victory,death};
}

export function resolveSupply(g:Run,id:SupplyId,graveItems:OwnedGear[]=[]):BattleResolution{
  let victory:BattleEnemy|null=null,death:FinishDetail|null=null;
  const win=(run:Run,battle:BattleEnemy):Run=>{victory=battle;return victoryRun(run,battle,graveItems);};
  const act=(g:Run):Run=>{if(!g||g.phase!=="battle"||!g.battle||g.pendingEnemyTurn)return g;const unavailable=supplyUnavailableReason(g,id);if(unavailable)return{...g,message:`${supplyName(id)}は使えない：${unavailable}。`};let b={...g.battle},next={...g,supplies:{...g.supplies,[id]:(g.supplies[id]??1)-1}},message="";const st=stats(g);if(id==="c2")return queueEnemyTurn({...next,statuses:[]},b,"万能薬ですべての状態異常を解除した。");if(id==="c7")return{...next,phase:"explore",battle:null,pendingEnemyTurn:null,enemies:retreatEnemyAfterEscape(g.map,g.player,g.enemies,b.id),message:"煙玉の煙に紛れ、敵を振り切った。"};if(id==="c8"||id==="c9"){const target=id==="c8"?"curse":"bleed",heal=Math.min(12,st.maxHp-g.hp),statuses=g.statuses.filter(status=>status.kind!==target);return queueEnemyTurn({...next,hp:g.hp+heal,statuses},b,`${supplyName(id)}で${statusName[target]}を解除し、HPを${heal}回復した。`);}if(id==="c10"){const recovered=Math.min(10,st.maxMp-g.mp);return queueEnemyTurn({...next,mp:g.mp+recovered},b,`星蜜でMPを${recovered}回復した。`);}const record=monsterRecordFor(b.catalogId),bossTactic=b.boss?BOSS_TACTICS[g.floor]:undefined,trait=bossTactic?.trait??record.trait,affinityTarget=bossTactic??record,damageKind:DamageKind=id==="c4"?"fire":id==="c5"?"ice":"lightning",baseDamage=id==="c4"?Math.max(20,Math.ceil(st.atk*.85)+g.floor*2):id==="c5"?Math.max(18,Math.ceil(st.atk*.7)+Math.ceil(g.floor*1.7)):Math.max(24,st.atk+Math.ceil(g.floor*2.1));let [r,seed]=nextRandom(g.seed);next.seed=seed;if(trait==="fireAbsorb"&&damageKind==="fire"){const absorbed=Math.min(b.maxHp-b.hp,Math.max(1,Math.ceil(baseDamage*.65)));b.hp+=absorbed;return queueEnemyTurn(next,b,`${b.name}は火炎瓶を吸収し、HPを${absorbed}回復した！`);}if(trait==="magicMirror"){const reflected=Math.max(1,Math.ceil(baseDamage*.3)),hp=Math.max(0,g.hp-reflected);if(hp<=0){const deathMessage=`${b.name}の鏡面が${supplyName(id)}を反射。${reflected}の傷で倒れた……`;death={cause:"reflect",intent:b.intent};return{...next,hp:0,battle:b,message:deathMessage};}return queueEnemyTurn({...next,hp},b,`${b.name}の鏡面が${supplyName(id)}を反射。${g.name}は${reflected}の傷！`);}const affinity=damageMultiplierFor(affinityTarget,damageKind),guardScale=b.intent==="guard"?(trait==="shell"?.18:trait==="shieldWall"?.25:.55):1,damage=Math.max(1,Math.floor(baseDamage*affinity*guardScale)),skip=id==="c5"&&r<.35;b.hp-=damage;message=`${supplyName(id)}が炸裂し、${damage}の傷！${affinity>1?" 弱点を突いた！":affinity<1?" 耐性に阻まれた。":""}${guardScale<1?" 敵の防御に阻まれた。":""}${skip?" 冷気で敵の動きが止まった！":""}`;if(b.hp<=0)return win(next,b);return queueEnemyTurn(next,b,message,skip);};
  const next=act(g);
  return {run:withBattleNotice(g,next,id,undefined,Boolean(victory),Boolean(death)),victory,death};
}
