import type { PassiveKey } from "./items";
import type { QuestKey } from "./i18n";
import type { JobKey } from "../shared/jobs";
export type { JobKey } from "../shared/jobs";
export type GameNotice = { type: "chest"; category: string; itemId?: string; amount?: number; converted?: boolean } | { type: "combat"; command: string; enemyIntent?: EnemyIntent; playerDamage: number; enemyDamage: number; healing: number; enemyHealing: number; mpChange: number; status: StatusKind[]; victory: boolean; dead: boolean } | { type: "message"; en: string };
export type Phase = "explore" | "battle" | "shop" | "bossChoice" | "relicChoice" | "recoveryChoice" | "ending";
export type Point = { x: number; y: number };
export type Tile = "#" | "." | ">" | "$" | "S";
export type GearKind = "weapon" | "armor" | "accessory";
export type EnemyIntent = "attack" | "heavy" | "guard" | "charge" | "status";
export type StatusKind = "poison" | "bleed" | "curse" | "blind" | "paralysis";
export type Status = { kind: StatusKind; turns: number };
export type SupplyId = "c2" | "c4" | "c5" | "c6" | "c7" | "c8" | "c9" | "c10";
export type BattleFx = "" | "slash" | "magic" | "heal" | "blast" | "vanish";
export type Gear = { id: string; name: string; kind: GearKind; tier: number; price: number; atk?: number; def?: number; hp?: number; mp?: number; passive?: PassiveKey; passiveValue?: number };
export type OwnedGear = Gear & { uid: number; loaned?: boolean };
export type DungeonEnemy = { id: number; x: number; y: number; kind: number; boss: boolean; graveEater?: boolean };
export type BattleEnemy = DungeonEnemy & { name: string; catalogId: string; hp: number; maxHp: number; atk: number; def: number; gold: number; exp: number; intent: EnemyIntent; turn: number; traitUsed?: boolean };
export type PendingEnemyTurn = { battle: BattleEnemy; message: string; skip: boolean };
export type RunRoute = "normal" | "descent";
export type Run = {
  runId: string; chestsOpened: number; notice?: GameNotice; name: string; job: JobKey; phase: Phase; floor: number; level: number; exp: number; hp: number; mp: number;
  gold: number; totalGold: number; kills: number; bosses: number; seed: number; nextUid: number; map: Tile[][]; seen: boolean[][];
  player: Point; enemies: DungeonEnemy[]; opened: number[]; inventory: OwnedGear[]; equipment: Record<GearKind, OwnedGear | null>;
  potions: number; bombs: number; supplies: Partial<Record<SupplyId,number>>; combo: number; relics: string[]; testMode: boolean; testPower: boolean; route: RunRoute; quest: QuestKey; recovery: OwnedGear[]; shopPotionAvailable: boolean; battle: BattleEnemy | null; pendingEnemyTurn: PendingEnemyTurn | null; guard: number; statuses: Status[]; message: string;
};
export type Grave = { floor: number; items: OwnedGear[] };
export type Meta = { version: 2; bestFloor: number; bestScore: number; totalKills: number; cleared: boolean; unlocked: JobKey[]; jobBest: Partial<Record<JobKey, number>>; mastery: Partial<Record<JobKey, number>>; titles: string[]; grave: Grave | null; bestiary: Record<string,number>; itemDiscovery: Record<string,number>; deepestSafeFloor: number };
export type DeathCause = "heavy" | "status" | "reflect" | "enemy";
export type DeathDetail = { cause: DeathCause; enemyCatalogId: string; enemyFloor: number; boss: boolean; graveEater?: boolean; intent: EnemyIntent };
export type FinishDetail = { cause?: DeathCause; intent?: EnemyIntent };
export type QuestProgress = { value: number; target: number; complete: boolean };
export type Result = { reason: "dead" | "return" | "abandon" | "clear"; floor: number; score: number; kills: number; bosses: number; unlocked: JobKey[]; name: string; job: JobKey; testMode: boolean; route: RunRoute; quest: QuestKey; questProgress: number; questTarget: number; questComplete: boolean; mastery: number; masteryGain: number; nextMastery: number | null; graveItems: number; death?: DeathDetail };
