"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Job = "warrior"|"thief"|"priest"|"mage"|"knight"|"sage";
type Status = "毒"|"出血"|"呪い"|"暗闇"|"麻痺";
type Intent = "攻撃"|"強襲"|"毒牙"|"呪詛"|"暗闇"|"麻痺"|"休息";
type GearKind = "武器"|"防具"|"装飾"|"消耗品"|"遺物";
type Item = { id:string; name:string; kind:GearKind; tier:number; atk:number; def:number; hp:number; price:number };
type Enemy = { id:number; base:number; variant:number; boss:boolean; hp:number; max:number; atk:number; intent:Intent };
type Run = { name:string; job:Job; quest:string; floor:number; hp:number; mp:number; lv:number; exp:number; gold:number; potions:number; gear:Item[]; equipped:Item[]; enemies:Enemy[]; battle:Enemy|null; statuses:Status[]; guard:boolean; kills:number; bosses:number; seed:number; message:string; phase:"map"|"battle"|"shop"|"ending" };
type Meta = { bestFloor:number; bestScore:number; kills:number; codex:number[]; titles:string[]; mastery:Partial<Record<Job,number>>; graves:{floor:number; item?:Item; date:string}[] };
const RUN="chika-hyakkei-run-v2", META="chika-hyakkei-meta-v2";
const jobs:Record<Job,{name:string;color:string;hp:number;mp:number;atk:number;def:number;skills:[string,string]}>={
 warrior:{name:"戦士",color:"#cb744d",hp:42,mp:8,atk:9,def:5,skills:["強打","防御"]}, thief:{name:"盗賊",color:"#d1b55e",hp:34,mp:12,atk:8,def:3,skills:["連撃","煙幕"]}, priest:{name:"僧侶",color:"#c9d9b4",hp:36,mp:18,atk:5,def:5,skills:["治療","結界"]}, mage:{name:"魔法使い",color:"#9f91d8",hp:29,mp:24,atk:4,def:2,skills:["火球","氷結"]}, knight:{name:"騎士",color:"#7baec5",hp:48,mp:12,atk:8,def:8,skills:["盾打ち","鉄壁"]}, sage:{name:"賢者",color:"#bf8bca",hp:37,mp:27,atk:6,def:5,skills:["大治療","雷撃"]}
};
const baseNames=["洞ミミズ","苔スライム","骨ネズミ","夜コウモリ","穴ゴブリン","岩トカゲ","亡者の鎧","火喰い虫","影オオカミ","深層の目","鉄蟹","泥人形","蝋燭鬼","鉱夫の影","白蛇","菌糸獣","煤の騎士","穴蜘蛛","水晶虫","忘却の手","崩れ獣","吊り人","石面","墓守","虚ろの王"];
const variants=["通常","凶暴","呪染","深淵"];
const zoneNames=["忘れ井戸","苔むす坑道","鉄の廃坑","灰の礼拝堂","硝子洞","血の水路","沈黙の鉱脈","逆さ墓地","星喰いの裂け目","奈落の王座"];
const bossNames=["井戸の主","苔冠の母","鉄鎚の巨人","灰の司祭","硝子の蛇王","血河の監視者","無言の採掘王","逆葬の女王","星喰いの獣","百景の底・虚無王"];
const quests=["失われた標本を3つ持ち帰る","呪染の魔物を5体討つ","100階の虚無王を討つ"];
const prefixes={武器:["錆びた","銅の","鉄の","月影の","竜骨の","深淵の"],防具:["旅布の","革の","鎖の","石守の","星守の","奈落の"],装飾:["木彫りの","力の","守りの","月白の","王家の","虚無の"]};
const itemNames={武器:["短剣","剣","斧","槌","杖"],防具:["服","鎧","外套","法衣","胸当て"],装飾:["環","指輪","首飾り","鈴","印"]};
const ITEMS:Item[]=( ["武器","防具","装飾"] as const).flatMap((kind,ki)=>Array.from({length:kind==="装飾"?20:30},(_,i)=>({id:`${ki}-${i}`,name:`${prefixes[kind][Math.floor(i/5)]}${itemNames[kind][i%5]}`,kind,tier:i+1,atk:kind==="武器"?2+Math.floor(i/3):kind==="装飾"&&i%3===0?1+Math.floor(i/5):0,def:kind==="防具"?1+Math.floor(i/4):kind==="装飾"&&i%3===1?1+Math.floor(i/6):0,hp:kind==="装飾"&&i%3===2?4+i:0,price:12+i+Math.floor(i/5)*4}))).concat(Array.from({length:10},(_,i)=>({id:`c${i}`,name:`${["浄化","煙玉","火油","氷片","解毒","止血","灯火","聖水","転移","月露"][i]}薬`,kind:"消耗品" as GearKind,tier:i+1,atk:0,def:0,hp:0,price:12+i*3})),Array.from({length:10},(_,i)=>({id:`r${i}`,name:`${["坑道","苔冠","鉄鎚","灰","硝子","血河","沈黙","逆葬","星喰い","百景"][i]}の遺物`,kind:"遺物" as GearKind,tier:i+1,atk:1+i,def:1+Math.floor(i/2),hp:3+i*2,price:30+i*4})));
const rand=(seed:number)=>{const n=(seed*1664525+1013904223)>>>0;return [n/4294967296,n] as const};
const newIntent=(seed:number):Intent=>["攻撃","攻撃","強襲","毒牙","呪詛","暗闇","麻痺","休息"][Math.floor(rand(seed)[0]*8)] as Intent;
const defaultMeta:Meta={bestFloor:0,bestScore:0,kills:0,codex:[],titles:[],mastery:{},graves:[]};
function stat(r:Run){const j=jobs[r.job],g=r.equipped;return{hp:j.hp+(r.lv-1)*4+g.reduce((a,x)=>a+x.hp,0),mp:j.mp+(r.lv-1)*2,atk:j.atk+(r.lv-1)+g.reduce((a,x)=>a+x.atk,0),def:j.def+Math.floor((r.lv-1)/2)+g.reduce((a,x)=>a+x.def,0)}}
function makeEnemy(floor:number,index:number,boss=false):Enemy{const base=boss?24:(floor*3+index*7)%25,variant=Math.min(3,Math.floor((floor-1)/25));const scale=1+floor*.12+(boss?floor*.08:0),hp=Math.floor((boss?44:13)*scale);return{id:index+floor*100,base,variant,boss,hp,max:hp,atk:Math.floor((boss?5.8:2.7)+floor*.38+(variant*.9)),intent:newIntent(floor*99+index)}}
function startRun(name:string,job:Job,quest:string,seed=Date.now()):Run{const j=jobs[job];return{name:name||"ナナシ",job,quest,floor:1,hp:j.hp,mp:j.mp,lv:1,exp:0,gold:12,potions:1,gear:[],equipped:[],enemies:[makeEnemy(1,0),makeEnemy(1,1),makeEnemy(1,2)],battle:null,statuses:[],guard:false,kills:0,bosses:0,seed,message:"地下1階、忘れ井戸。敵の次行動を読め。",phase:"map"}}
function effect(intent:Intent):Status|undefined{return({毒牙:"毒",呪詛:"呪い",暗闇:"暗闇",麻痺:"麻痺"})[intent]}

export default function Home(){
 const [meta,setMeta]=useState<Meta>(defaultMeta),[run,setRun]=useState<Run|null>(null),[name,setName]=useState(""),[job,setJob]=useState<Job>("warrior"),[quest,setQuest]=useState(quests[0]),[tab,setTab]=useState<"play"|"codex"|"records">("play"),[ready,setReady]=useState(false); const audio=useRef<AudioContext|null>(null);
 useEffect(()=>{try{setMeta({...defaultMeta,...JSON.parse(localStorage.getItem(META)||"null")});setRun(JSON.parse(localStorage.getItem(RUN)||"null"))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(META,JSON.stringify(meta))},[meta,ready]);useEffect(()=>{if(ready){if(run)localStorage.setItem(RUN,JSON.stringify(run));else localStorage.removeItem(RUN)}},[run,ready]);
 const sound=(f=220)=>{try{const c=audio.current??new AudioContext();audio.current=c;const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.08);o.stop(c.currentTime+.08)}catch{}};
 const finish=(dead=false,r=run)=>{if(!r)return;const score=r.floor*1000+r.kills*80+r.bosses*1500;const grave=dead?{floor:r.floor,item:[...r.equipped,...r.gear][0],date:new Date().toLocaleDateString()}:undefined;setMeta(m=>({...m,bestFloor:Math.max(m.bestFloor,r.floor),bestScore:Math.max(m.bestScore,score),kills:m.kills+r.kills,codex:[...new Set([...m.codex,...r.enemies.map(e=>e.base+e.variant*25)])],titles:[...new Set([...m.titles,r.floor>=100?"百景を踏破せし者":r.floor>=50?"深層踏破者":"坑道の旅人"])],mastery:{...m.mastery,[r.job]:Math.max(m.mastery[r.job]||0,r.floor)},graves:grave?[grave,...m.graves].slice(0,12):m.graves}));setRun(null);sound(dead?70:660)};
 const descend=(r:Run)=>{if(r.enemies.length)return{...r,message:"この階の敵を倒さなければ、階段は開かない。"};if(r.floor>=100)return{...r,phase:"ending" as const,message:"虚無王は砕けた。百の景色が、地上の光へ変わる。"};const floor=r.floor+1,st=stat(r),boss=floor%10===0;return{...r,floor,hp:Math.min(st.hp,r.hp+Math.ceil(st.hp*.18)),mp:Math.min(st.mp,r.mp+3),enemies:Array.from({length:boss?4:3},(_,i)=>makeEnemy(floor,i,boss&&i===3)),battle:null,statuses:r.statuses.filter(x=>x!=="麻痺"),message:`地下${floor}階、${zoneNames[Math.floor((floor-1)/10)]}。${boss?`階層主「${bossNames[floor/10-1]}」がいる。`:""}`,phase:"map" as const};};
 const win=(r:Run,e:Enemy)=>{let exp=r.exp+8+r.floor,lv=r.lv,hp=r.hp,mp=r.mp;while(exp>=lv*18){exp-=lv*18;lv++;hp+=4;mp+=2}const final=e.boss&&r.floor===100;return{...r,lv,exp,hp,mp,battle:null,phase:final?"ending" as const:"map" as const,kills:r.kills+1,bosses:r.bosses+(e.boss?1:0),gold:r.gold+5+r.floor,enemies:r.enemies.filter(x=>x.id!==e.id),message:final?"虚無王を討ち滅ぼした。百景の終わりへ。":`${e.boss?bossNames[Math.floor((r.floor-1)/10)]:variants[e.variant]+baseNames[e.base]}を倒した。敵の図鑑が記された。`}}
 const act=(kind:"attack"|"guard"|"skill1"|"skill2"|"potion")=>setRun(r=>{if(!r?.battle)return r;let e={...r.battle},n={...r},s=stat(r),damage=0,heal=0,guard=false,skip=false;const blinded=r.statuses.includes("暗闇");if(kind==="attack")damage=Math.max(1,s.atk-e.atk/4-(blinded?3:0));if(kind==="guard"){guard=true;n.message="防御！ 予兆を受け止める構え。"}if(kind==="potion"){if(!r.potions)return{...r,message:"回復薬はない。"};heal=Math.max(18,Math.ceil(s.hp*.45));n.potions--;n.hp=Math.min(s.hp,n.hp+heal);n.message=`回復薬で${heal}回復。しかし敵は反撃する！`;}if(kind.startsWith("skill")){const second=kind==="skill2",cost=second?4:3;if(n.mp<cost)return{...r,message:"MPが足りない。"};n.mp-=cost;if(r.job==="warrior"&&second)guard=true;else if(r.job==="priest"&&!second)heal=16+r.lv*2;else if(r.job==="priest"&&second)guard=true;else if(r.job==="thief"&&second)skip=true;else if(r.job==="mage"&&second)skip=true;else damage=(second?1.8:1.5)*s.atk+4+r.lv*2;n.hp=Math.min(s.hp,n.hp+heal);n.message=`${jobs[r.job].skills[second?1:0]}！`;}e.hp-=Math.floor(damage);if(e.hp<=0){sound(620);return win(n,e)}const intent=e.intent;let taken=0;if(!skip&&intent!=="休息"){const raw=intent==="強襲"?e.atk*1.55:e.atk; taken=Math.max(1,Math.floor((raw-s.def)*(guard?.32:1)*(r.statuses.includes("呪い")?1.2:1)));n.hp-=taken;const stt=effect(intent);if(stt&&!n.statuses.includes(stt))n.statuses=[...n.statuses,stt];if(intent==="毒牙"&&!n.statuses.includes("毒"))n.statuses=[...n.statuses,"毒"]}if(n.statuses.includes("毒"))n.hp-=2;if(n.statuses.includes("出血"))n.hp-=1;e.intent=newIntent(n.seed+e.hp+e.id);n.seed=(n.seed*1103515245+12345)>>>0;n.guard=false;n.battle=e;n.message+=skip?" 敵の行動を封じた！":` 敵は${intent}、${taken}ダメージ。次は「${e.intent}」。`;sound(kind==="guard"?150:320);if(n.hp<=0){setTimeout(()=>finish(true,{...n,hp:0}),0);return{...n,hp:0}}return n});
 const openShop=()=>setRun(r=>r?{...r,phase:"shop",message:"3階ごとの坑道商店。回復薬は一店につき1個。"}:r);
 const buyPotion=()=>setRun(r=>{if(!r)return r;const price=12+((r.floor/3|0)%4)*12;if(r.potions>=3)return{...r,message:"回復薬は3個まで。"};if(r.gold<price)return{...r,message:"金貨が足りない。"};return{...r,gold:r.gold-price,potions:r.potions+1,message:`回復薬を${price}Gで買った。`}});
 const recovery=meta.graves[0]; if(!ready)return null; const st=run&&stat(run),enemy=run?.battle;
 return <main className="shell"><header><div><span className="kicker">TACTICAL ROGUELITE · 100 FLOORS</span><h1>地下百景</h1></div><div className="records"><span>最高 <b>{meta.bestFloor}F</b></span><button onClick={()=>setTab("codex")}>図鑑 {meta.codex.length}/100</button><button onClick={()=>setTab("records")}>記録</button></div></header>
 {!run?<section className="start-panel"><div className="title-copy"><div className="shaft"/><p>百の景色を越え、虚無王を討て。<br/>死ねば全てを失う。</p><small>回復薬は最大3個。敵の予兆を読め。</small></div><div className="setup"><label>探索者の名前<input value={name} maxLength={8} onChange={e=>setName(e.target.value)} placeholder="ナナシ"/></label><p className="choose-label">職業（熟練度は初期装備・色・選択肢を解放）</p><div className="jobs">{(Object.keys(jobs) as Job[]).map(k=><button key={k} className={job===k?"selected":""} onClick={()=>setJob(k)} style={{borderColor:job===k?jobs[k].color:undefined}}><b style={{color:jobs[k].color}}>◆</b><span>{jobs[k].name}</span><small>{jobs[k].skills.join(" / ")}　熟練 {meta.mastery[k]||0}F</small></button>)}</div><p className="choose-label">地下依頼を1件選ぶ</p><div className="quests">{quests.map(q=><button key={q} className={quest===q?"selected":""} onClick={()=>setQuest(q)}>{q}</button>)}</div>{recovery&&<p className="grave-note">遺品喰らいの墓標：地下{recovery.floor}階。倒せば「{recovery.item?.name||"遺品"}」を1個回収できる。</p>}<button className="primary start" onClick={()=>{setRun(startRun(name,job,quest));setTab("play");sound(500)}}>地下へ降りる</button></div></section>:<><section className="game-layout"><div className="game-card"><div className="floor-head"><span>地下 <b>{run.floor}</b> 階 · {zoneNames[(run.floor-1)/10|0]}</span><span>{jobs[run.job].name}・{run.name}</span><span>{run.floor%3===0?"商店あり":"探索中"}</span></div><div className={`map biome-${(run.floor-1)/10|0}`}><div className="scene"><span className="floor-number">{run.floor}</span>{run.enemies.map((e,i)=><button className={`map-monster species-${e.base%10} variant-${e.variant} ${e.boss?"map-boss":""}`} key={e.id} onClick={()=>setRun(r=>r?{...r,battle:e,phase:"battle",message:`${e.boss?bossNames[(r.floor-1)/10|0]:variants[e.variant]+baseNames[e.base]}が現れた。`}:r)} aria-label="敵と戦う"><i/><i/><i/></button>)}<span className="pixel-player"><i/><i/><i/><i/><i/></span></div></div><div className="message"><i>◆</i><p>{run.message}</p></div><div className="dpad"><button onClick={()=>setRun(descend)}>▼ 次の階へ</button>{run.floor%3===0&&<button onClick={openShop}>商店へ</button>}<button onClick={()=>finish(false)}>帰還する</button></div></div><aside className="status"><h2 style={{color:jobs[run.job].color}}>◆ {jobs[run.job].name}</h2><div className="meters"><label>HP <b>{run.hp}/{st?.hp}</b><i><em style={{width:`${run.hp/(st?.hp||1)*100}%`}}/></i></label><label>MP <b>{run.mp}/{st?.mp}</b><i><em className="mp" style={{width:`${run.mp/(st?.mp||1)*100}%`}}/></i></label></div><div className="numbers"><span>LV <b>{run.lv}</b></span><span>金貨 <b>{run.gold}G</b></span><span>攻撃 <b>{st?.atk}</b></span><span>守備 <b>{st?.def}</b></span><span>薬 <b>{run.potions}/3</b></span><span>討伐 <b>{run.kills}</b></span></div><h3>状態</h3><p>{run.statuses.length?run.statuses.join("・"):"異常なし"}</p><h3>依頼</h3><p>{run.quest}</p><h3>装備</h3><p>{run.equipped.length?run.equipped.map(x=>x.name).join("・"):"なし"}</p></aside></section>
 {enemy&&<div className="overlay battle-overlay"><div className="modal battle"><span className="modal-kicker">ENCOUNTER · 次行動を読む</span><div className={`monster species-${enemy.base%10} variant-${enemy.variant} ${enemy.boss?"king":""}`}><i/><i/><i/><i/></div><h2>{enemy.boss?bossNames[(run.floor-1)/10|0]:`${variants[enemy.variant]} ${baseNames[enemy.base]}`}</h2><div className="enemy-hp"><i style={{width:`${enemy.hp/enemy.max*100}%`}}/></div><div className={`intent intent-${enemy.intent}`}><small>敵の次行動</small><b>{enemy.intent}</b><span>{enemy.intent==="強襲"?"大ダメージ。防御が有効":enemy.intent==="休息"?"攻め時":enemy.intent==="毒牙"?"毒を受ける。短期決戦を":"防御・技・回復を判断"}</span></div><div className="battle-actions"><button onClick={()=>act("attack")}>攻撃</button><button onClick={()=>act("guard")}>防御</button><button onClick={()=>act("skill1")}>{jobs[run.job].skills[0]}</button><button onClick={()=>act("skill2")}>{jobs[run.job].skills[1]}</button><button onClick={()=>act("potion")}>回復薬 ×{run.potions}</button></div></div></div>}
 {run.phase==="shop"&&<div className="overlay"><div className="modal shop"><span className="modal-kicker">SHOP · 階層{(run.floor-1)/10|0+1}の品揃え</span><h2>坑道商人</h2><p>回復薬は一店につき1個。所持上限は3個。</p><div className="wares"><button onClick={buyPotion}><span>回復薬<small>最大HP45%・最低18回復／使うと反撃</small></span><b>{12+((run.floor/3|0)%4)*12}G</b></button></div><button className="primary" onClick={()=>setRun(r=>r?{...r,phase:"map"}:r)}>探索へ戻る</button></div></div>}
 {run.phase==="ending"&&<div className="overlay"><div className="modal choice"><span className="modal-kicker">THE HUNDREDTH VIEW</span><h2>虚無王は滅びた</h2><p>百の地下景は、あなたの足跡を覚えている。<br/>称号「百景を踏破せし者」を獲得。</p><button className="primary" onClick={()=>finish(false)}>エンディングへ</button></div></div>}</>}
 {tab==="codex"&&!run&&<div className="overlay"><div className="modal"><h2>魔物図鑑 {meta.codex.length}/100</h2><p>{baseNames.map((n,i)=>variants.map((v,j)=><span className="codex-entry" key={v+n}>{meta.codex.includes(i+j*25)?`${v}${n}`:"？？？？"}</span>))}</p><button onClick={()=>setTab("play")}>閉じる</button></div></div>}{tab==="records"&&!run&&<div className="overlay"><div className="modal"><h2>冒険記録</h2><p>最高到達：{meta.bestFloor}F　最高得点：{meta.bestScore}</p><p>称号：{meta.titles.join("・")||"未獲得"}</p><p>墓データ：{meta.graves.map(g=>`${g.floor}F ${g.item?.name||"遺品"}`).join(" / ")||"なし"}</p><button onClick={()=>setTab("play")}>閉じる</button></div></div>}<footer>敵の予告を読み、防御・職業技・回復薬を使い分けよう　·　端末に自動保存</footer></main>
}
